name = "FinancialModelingPrepAPI"
uuid = "1cc2752e-21da-4391-ad89-feb43ead7358"
authors = ["Bernard Brenyah <pimpfada@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
